#!/usr/bin/env python3
"""Generate the Phase 4 ablation attribution report (bench/ablation/RESULTS.md).

Reads bench/ablation/manifest.toml (grid, references, landmarks) and each
cell's summary.json under bench/ablation/out/<label>/, then emits a
deterministic markdown report: provenance, per-cell totals, per-scene IDS
matrix, marginal table (each knob alone off baseline), stacked tables (finding
order + per-component path), and script-computed interaction notes. Every
number traces to a cell output file. The four reference landmarks are asserted
within manifest tolerance; any violation prints an error and exits non-zero.
A hand-written `## Analysis` section in the existing output file (heading to
EOF) is preserved verbatim across regeneration, so a human's prose survives
re-running the script; when no such section exists, a trailing `## Analysis`
placeholder heading is appended so the section is ready for the human. Output
is deterministic: the same out/ and the same existing output file always
regenerate the same bytes.

Usage:
  python3 bench/ablation/summarize.py [--out PATH]
"""
from __future__ import annotations

import argparse
import itertools
import json
import sys
from pathlib import Path

try:
    import tomllib
except ModuleNotFoundError:  # pragma: no cover - Python < 3.11
    import tomli as tomllib  # type: ignore[no-redef]

REPO_ROOT = Path(__file__).resolve().parents[2]
DEFAULT_MANIFEST = REPO_ROOT / "bench" / "ablation" / "manifest.toml"
OUT_ROOT = REPO_ROOT / "bench" / "ablation" / "out"
DEFAULT_REPORT = REPO_ROOT / "bench" / "ablation" / "RESULTS.md"
MANIFEST_REL = DEFAULT_MANIFEST.relative_to(REPO_ROOT)
OUT_REL = OUT_ROOT.relative_to(REPO_ROOT)
KNOBS = ["gate_m", "vel_cost_weight", "iou_weight", "min_birth_score"]
KNOB_SHORT = {
    "gate_m": "gate",
    "vel_cost_weight": "vel",
    "iou_weight": "iou",
    "min_birth_score": "birth",
}
PATH_STEPS = [
    ("+gate_m", "gate_m", {"gate_m": 1.5}),
    ("+vel", "vel_cost_weight", {"vel_cost_weight": 4.0}),
    ("+birth 0.5", "min_birth_score", {"min_birth_score": 0.5}),
    ("+iou", "iou_weight", {"iou_weight": 2.0}),
    ("+birth 0.7", "min_birth_score", {"min_birth_score": 0.7}),
]


def render_float(value: float) -> str:
    return str(float(value)).replace(".", "p")


def cell_label(knobs: dict) -> str:
    return (
        f"gate{render_float(knobs['gate_m'])}"
        f"-vel{render_float(knobs['vel_cost_weight'])}"
        f"-iou{render_float(knobs['iou_weight'])}"
        f"-birth{render_float(knobs['min_birth_score'])}"
    )


def materialize_cells(manifest: dict) -> list[dict]:
    defaults = dict(manifest["defaults"])
    levels = manifest["grid"]["levels"]
    expected_keys = set(json.loads((REPO_ROOT / "core" / "config" / "default.json").read_text(encoding="utf-8")))
    cells = []
    for combo in itertools.product(*(levels[k] for k in KNOBS)):
        overrides = dict(zip(KNOBS, combo))
        config = {**defaults, **overrides}
        if set(config) != expected_keys:
            raise RuntimeError(
                f"materialized config keys {sorted(config)} != default.json keys {sorted(expected_keys)}"
            )
        cells.append({"config": config, "knobs": overrides, "label": cell_label(overrides)})
    return cells


def load_references(manifest: dict) -> dict:
    refs = dict(manifest["reference"])
    if isinstance(refs.get("alias"), dict):
        refs.pop("alias")
    return refs


def load_summary(label: str) -> dict:
    path = OUT_ROOT / label / "summary.json"
    if not path.is_file():
        raise SystemExit(
            f"error: missing summary.json for cell {label!r}: expected {path}\n"
            f"rerun `python scripts/ablate.py` to materialize the full 24-cell grid"
        )
    return json.loads(path.read_text(encoding="utf-8"))


def fmt_mota(v: float) -> str:
    return f"{v:.4f}"


def signed_int(v: int) -> str:
    return f"{v:+d}" if v else "0"


def signed_mota(v: float) -> str:
    return f"{v:+.4f}" if v else "0.0000"


def ids_effect(delta: int) -> str:
    if delta < 0:
        return f"cuts total IDS by {-delta}"
    if delta > 0:
        return f"raises total IDS by {delta}"
    return "leaves total IDS unchanged"


def md_table(headers: list[str], rows: list[list]) -> list[str]:
    lines = ["| " + " | ".join(headers) + " |", "|" + "|".join("---" for _ in headers) + "|"]
    for row in rows:
        lines.append("| " + " | ".join(str(c) for c in row) + " |")
    return lines


def build_report(manifest: dict, cells_by_label: dict, refs: dict, summaries: dict) -> tuple[str, list]:
    meta = manifest["meta"]
    tolerance = manifest["landmarks"]["tolerance_ids"]

    lines: list[str] = []
    lines.append("# Phase 4 Ablation Grid — Attribution Report")
    lines.append("")
    lines.append(
        f"Machine-generated by `bench/ablation/summarize.py` from `{MANIFEST_REL}` "
        f"and the per-cell `summary.json` outputs under `{OUT_REL}/<label>/`. "
        f"Do not hand-edit; regenerate with `python3 bench/ablation/summarize.py`."
    )
    lines.append("")
    lines.append("## Provenance")
    lines.append("")
    lines.append(f"- Split: {meta['split']}")
    lines.append(
        f"- Detections: {meta['detections_file']} ({meta['detections_source']})"
    )
    lines.append(
        f"- Tracking classes: {meta['tracking_classes']} — "
        + ", ".join(meta["tracking_classes_list"])
    )
    lines.append(f"- Ingest score filter: >= {meta['ingest_score_filter']}")
    lines.append(f"- Normalized root: {meta['normalized_root']}")
    lines.append(
        f"- Tracker build: {meta['tracker_build_flavor']} "
        f"(TRACKBENCH_STAGE_TIMING={meta['tracker_build_stage_timing']}, "
        f"{meta['tracker_build_opt']})"
    )
    lines.append(f"- Seed: {meta['seed']}")
    lines.append(f"- Python: {meta['python_version']}")
    lines.append(
        f"- Eval stack: {meta['eval_stack']} ({', '.join(meta['eval_stack_pins'])})"
    )

    levels = manifest["grid"]["levels"]
    grid_n = 1
    for k in KNOBS:
        grid_n *= len(levels[k])

    lines.append("")
    lines.append("## Per-cell table")
    lines.append("")
    lines.append(
        "Full factorial over `gate_m` ("
        + f"{len(levels['gate_m'])} levels) × `vel_cost_weight` "
        f"({len(levels['vel_cost_weight'])}) × `iou_weight` "
        f"({len(levels['iou_weight'])}) × `min_birth_score` "
        f"({len(levels['min_birth_score'])}) = {grid_n} cells; everything else "
        "fixed at manifest `[defaults]`."
    )
    lines.append("")
    headers = ["cell label"] + KNOBS + ["total_ids", "total_mota", "n_failures"]
    rows = []
    for label in sorted(cells_by_label):
        knobs = cells_by_label[label]["knobs"]
        summary = summaries[label]
        n_failures = sum(scene["n_failures"] for scene in summary["scenes"].values())
        rows.append(
            [label, *[str(float(knobs[k])) for k in KNOBS],
             summary["total_ids"], fmt_mota(summary["total_mota"]), n_failures]
        )
    lines.extend(md_table(headers, rows))

    scene_names = sorted(next(iter(summaries.values()))["scenes"])

    lines.append("")
    lines.append(f"## Per-scene IDS matrix ({grid_n} cells × {len(scene_names)} scenes)")
    lines.append("")
    lines.append("Per-scene ID switches per cell; TOTAL is the cell `total_ids`.")
    lines.append("")
    headers = ["cell label", *scene_names, "TOTAL"]
    rows = []
    for label in sorted(cells_by_label):
        summary = summaries[label]
        rows.append(
            [label, *[summary["scenes"][scene]["ids"] for scene in scene_names],
             summary["total_ids"]]
        )
    lines.extend(md_table(headers, rows))

    baseline_knobs = dict(refs["baseline"])
    baseline_label = cell_label(baseline_knobs)
    baseline = summaries[baseline_label]

    marginal_rows = []
    for knob in KNOBS:
        non_base = [v for v in levels[knob] if v != baseline_knobs[knob]]
        for value in non_base:
            knobs = {**baseline_knobs, knob: value}
            label = cell_label(knobs)
            summary = summaries[label]
            row_name = f"{KNOB_SHORT[knob]} {value} only" if len(non_base) > 1 else f"{KNOB_SHORT[knob]} only"
            marginal_rows.append(
                {
                    "row_name": row_name,
                    "knob": knob,
                    "value": value,
                    "label": label,
                    "summary": summary,
                    "d_ids": summary["total_ids"] - baseline["total_ids"],
                    "d_mota": summary["total_mota"] - baseline["total_mota"],
                }
            )

    lines.append("")
    lines.append("## Marginal table (each knob flipped alone off baseline)")
    lines.append("")
    lines.append(
        f"Baseline: `{baseline_label}` (total_ids {baseline['total_ids']}, "
        f"total_mota {fmt_mota(baseline['total_mota'])})."
    )
    lines.append("")
    headers = ["row", "knob", "value", "total_ids", "ΔIDS vs baseline",
               "total_mota", "ΔMOTA vs baseline"]
    rows = []
    for m in marginal_rows:
        rows.append(
            [m["row_name"], m["knob"], str(float(m["value"])),
             m["summary"]["total_ids"], signed_int(m["d_ids"]),
             fmt_mota(m["summary"]["total_mota"]), signed_mota(m["d_mota"])]
        )
    lines.extend(md_table(headers, rows))

    ref_names = list(meta["status"]["reference_cells"])
    for name in ref_names:
        if name not in refs:
            raise SystemExit(
                f"error: reference cell {name!r} (meta.status.reference_cells) "
                "not defined in manifest [reference]"
            )
        if name not in manifest["landmarks"]:
            raise SystemExit(
                f"error: reference cell {name!r} has no expected_ids landmark "
                "in manifest [landmarks]"
            )

    lines.append("")
    lines.append(
        f"## Stacked table A — finding order ({' → '.join(ref_names)})"
    )
    lines.append("")
    headers = ["step", "cell label", "measured total_ids", "incremental ΔIDS",
               "expected (landmark)", "Δ vs expected"]
    rows = []
    violations = []
    prev_ids = None
    for name in ref_names:
        label = cell_label(refs[name])
        measured = summaries[label]["total_ids"]
        expected = manifest["landmarks"][name]["expected_ids"]
        inc = "—" if prev_ids is None else signed_int(measured - prev_ids)
        rows.append(
            [name, label, measured, inc, expected, signed_int(measured - expected)]
        )
        if abs(measured - expected) > tolerance:
            violations.append((name, label, measured, expected))
        prev_ids = measured
    lines.extend(md_table(headers, rows))
    lines.append("")
    if violations:
        gate_line = (
            f"Reproducibility gate: FAIL — reference cell total_ids outside "
            f"±{tolerance} of landmark: "
            + "; ".join(f"{name} ({label}) measured {measured} vs expected {expected}"
                        for name, label, measured, expected in violations)
        )
    else:
        gate_line = (
            f"Reproducibility gate: PASS — all reference cells within ±{tolerance} "
            "IDS of their landmarks."
        )
    lines.append(gate_line)

    steps = [("baseline", "—", dict(baseline_knobs), None, None)]
    knobs = dict(baseline_knobs)
    for display, knob, override in PATH_STEPS:
        value = override[knob]
        if value not in levels[knob]:
            raise SystemExit(
                f"error: component path step {display!r} uses {knob}={value} "
                f"which is not a manifest grid level ({levels[knob]})"
            )
        knobs = {**knobs, **override}
        steps.append((display, knob, dict(knobs), knob, value))
    for ref_name, idx in (("post001", 3), ("post002", 4), ("post003", 5)):
        actual = cell_label(steps[idx][2])
        expected_label = cell_label(refs[ref_name])
        if actual != expected_label:
            raise SystemExit(
                f"error: component path step {idx + 1} ({actual}) does not match "
                f"manifest reference {ref_name} ({expected_label})"
            )

    lines.append("")
    lines.append("## Stacked table B — per-component path (baseline → post003)")
    lines.append("")
    lines.append(
        "Each row turns one more knob on; the last three rows are the manifest "
        "references post001/post002/post003."
    )
    lines.append("")
    headers = ["step", "knob turned on", "cell label", "total_ids",
               "incremental ΔIDS", "total_mota", "incremental ΔMOTA"]
    rows = []
    b_deltas = {}
    prev_ids = prev_mota = None
    for display, knob_on, knobs, knob_key, knob_value in steps:
        label = cell_label(knobs)
        summary = summaries[label]
        ids, mota = summary["total_ids"], summary["total_mota"]
        if prev_ids is None:
            d_ids, d_mota = "—", "—"
        else:
            d_ids, d_mota = signed_int(ids - prev_ids), signed_mota(mota - prev_mota)
            if knob_key is not None:
                b_deltas[(knob_key, knob_value)] = (ids - prev_ids, mota - prev_mota)
        rows.append([display, knob_on, label, ids, d_ids, fmt_mota(mota), d_mota])
        prev_ids, prev_mota = ids, mota
    lines.extend(md_table(headers, rows))

    lines.append("")
    lines.append("## Interaction notes (marginal vs in-stack ΔIDS)")
    lines.append("")
    headers = ["knob", "value", "marginal ΔIDS", "in-stack ΔIDS",
               "difference (marginal − in-stack)"]
    rows = []
    for m in marginal_rows:
        in_stack = b_deltas.get((m["knob"], m["value"]))
        if in_stack is None:
            rows.append([m["knob"], str(float(m["value"])), signed_int(m["d_ids"]),
                         "n/a", "n/a"])
        else:
            rows.append([m["knob"], str(float(m["value"])), signed_int(m["d_ids"]),
                         signed_int(in_stack[0]), signed_int(m["d_ids"] - in_stack[0])])
    lines.extend(md_table(headers, rows))
    lines.append("")
    iou_marg = [m for m in marginal_rows if m["knob"] == "iou_weight"]
    if iou_marg:
        m = iou_marg[0]
        in_stack = b_deltas.get((m["knob"], m["value"]))
        if in_stack is not None:
            lines.append(
                f"iou marginal-vs-stacked: alone it {ids_effect(m['d_ids'])}; "
                f"in-stack it {ids_effect(in_stack[0])}."
            )

    return "\n".join(lines) + "\n", violations


def preserved_analysis(path: Path) -> str | None:
    """Return the existing `## Analysis` section (heading to EOF) verbatim, or None if absent."""
    if not path.is_file():
        return None
    lines = path.read_text(encoding="utf-8").splitlines(keepends=True)
    for i, line in enumerate(lines):
        if line.rstrip("\r\n") == "## Analysis":
            return "".join(lines[i:])
    return None


def parse_args(argv: list[str] | None) -> argparse.Namespace:
    p = argparse.ArgumentParser(
        prog="python3 bench/ablation/summarize.py",
        description="Generate the deterministic Phase 4 ablation attribution "
                    "report (marginal + stacked) from manifest.toml and per-cell "
                    "summary.json outputs.",
    )
    p.add_argument(
        "--manifest",
        default=str(DEFAULT_MANIFEST),
        help="ablation manifest TOML (default: %(default)s)",
    )
    p.add_argument(
        "--out",
        metavar="PATH",
        default=DEFAULT_REPORT,
        help="write markdown report to PATH (default: %(default)s)",
    )
    return p.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv)
    try:
        with open(args.manifest, "rb") as f:
            manifest = tomllib.load(f)
    except FileNotFoundError:
        print(f"error: manifest not found: {args.manifest}", file=sys.stderr)
        return 1
    except tomllib.TOMLDecodeError as e:
        print(f"error: {args.manifest}: {e}", file=sys.stderr)
        return 1

    cells = materialize_cells(manifest)
    cells_by_label = {c["label"]: c for c in cells}
    if len(cells_by_label) != 24:
        print(f"error: expected 24 unique cells, got {len(cells_by_label)}", file=sys.stderr)
        return 1
    refs = load_references(manifest)
    for name, knobs in refs.items():
        if cell_label(knobs) not in cells_by_label:
            print(
                f"error: reference {name!r} ({cell_label(knobs)}) is not "
                "materialized in the 24-cell grid",
                file=sys.stderr,
            )
            return 1

    summaries = {label: load_summary(label) for label in cells_by_label}
    scene_sets = {frozenset(s["scenes"]) for s in summaries.values()}
    if len(scene_sets) != 1:
        print(
            f"error: per-cell scene sets differ across cells "
            f"({len(scene_sets)} distinct scene sets)",
            file=sys.stderr,
        )
        return 1

    try:
        report, violations = build_report(manifest, cells_by_label, refs, summaries)
    except SystemExit as e:
        print(str(e), file=sys.stderr)
        return 1
    except KeyError as e:
        print(f"error: malformed summary.json — missing key {e}", file=sys.stderr)
        return 1

    preserved = preserved_analysis(Path(args.out))
    if preserved is None:
        report = report + "## Analysis\n\n"
    else:
        report = report + preserved

    Path(args.out).write_text(report, encoding="utf-8")
    print(f"wrote {args.out}", file=sys.stderr)
    if violations:
        tolerance = manifest["landmarks"]["tolerance_ids"]
        print(
            f"error: reproducibility gate FAILED — reference cell total_ids "
            f"outside ±{tolerance} of landmark:",
            file=sys.stderr,
        )
        for name, label, measured, expected in violations:
            print(
                f"  {name} ({label}): measured {measured}, expected {expected}",
                file=sys.stderr,
            )
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
